title: FRCC RoboTrace
description: FRCC Computer Science Club Robotics Race information site.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
include: ["_pages"]
permalink: /:title/

plugins:
  - jekyll-gist